### PR TITLE
Rebase PR #1

### PR DESCRIPTION
**Pull request by raphink**
This is a rebase of PR #1 in the hope of merging it eventually.

### CODE REVIEW

**Comment by raphink** [comment]
So this PR has been stuck for months (and the whole thing for years actually). I see @dotdoom is still maintaining his fork (and getting contribs, too) and the Debian maintainers have apparently decided to switch to the fork in Debian sid (I sent an email about this today).

I think we should really move on with this if we don't want to get in a hard-to-deal-with situation. Any thoughts @lutter, @domcleal?

**Comment by dotdoom** [comment]
There have been 2 PRs since Feb 20, 2014, but you know reviewing a simple diff an pushing "Merge & Close" button doesn't take much time ;)

I guess `AUGEAS_VERSION` is still not there; although I would be happy to merge all forks into one stable repo, we really need support from Augeas side. Otherwise this results in a lot of time wasted making workarounds.

**Comment by lutter** [comment]
Yes, I agree that it's terrible that this PR has been open for so long; what made the initial PR next to unreviewable was the 're-indent ruby files with 2 spaces' commit - there are patches in here that I would want to squash for clarity (like various patches changing 'Augeas.create' - for net-new code there's no reason to hvae that sort of thing, just provide the final Augeas.create function in a commit when it makes sense)

As for the version discussion, Augeas ships with a package config file, so you can use the output of `pkg-config --print-provides augeas` to determine the Augeas version, and try to figure out which constants are available based on that (not great, but should be workable)

I agree that the Rakefile needs to be cleaned up, and all the cruft around uploading releases etc. can go.

What I would like to see is a reworked version of this PR that (a) makes it very clear that the existing API is not affected by these changes and (b) makes it easier on the reviewer to follow what is happening and how the new API is built up (if you absolutely feel that code needs to be reformatted, please only do that as the very first or very last patch in the PR)

**Comment by raphink** [comment]
This issue has not progressed, still. So here's another suggestion to get things going:

* make the `augeas` gem the new official version
* make `ruby-augeas` deprecated, but keep it on rubygems
* move the current `master` branch to a `legacy` branch
* use @dotdoom code for the new master branch

At least, this will get us moving forward without breaking compatibility as long as users haven't migrated from the `ruby-augeas` gem. We could already move augeasproviders and the Puppet augeas type to the new gem.

**Comment by lutter** [comment]
I've once again looked at these patches, and the dotdoom fork, and am still completely dismayed by the situation that's been developing. The main reason why I looked was the fact that ruby-augeas does not build on OSX.

The reason that the dotdoom fork gets rid of hte old API is an absolute nonstarter. There is absolutely no way that we can get rid of the old API because of Puppet.

So I suggest the following: I'll take their changes to `extconf.rb` and open a separate PR with that, and after that we'll close this PR and any trying to merge the dotdoom fork wholesale. If people are interested in having an alternative, more Rubyesque API I'd expect them to open reviewable, reasonable PR's to that end rather than the nightmare that's been going on here for years.

**Comment by lutter** [comment]
Opened PR #6

**Comment by raphink** [comment]
@lutter what do you think of the proposal to migrate to the 'augeas' gem instead?

**Comment by lutter** [comment]
@raphink is all that effort worth it ? I am not sure that the advantages that the new API bring are worth that work. I had always hoped that we could have ruby-augeas offer both the old and the new API, and then make the two gems the same.

**Comment by raphink** [comment]
Right.. It's unfortunate that it never happened, and that the current situation has caused confusion, too.

**Comment by lutter** [comment]
This is not needed anymore. I just committed the equivalent functionality as part of PR #8

**Pull request closed without merging**
